image: node:18-alpine
stages:
  - install
  - docker
  - build
  - deploy

install-dependencies:
  stage: install
  script:
    - echo -e "http://nl.alpinelinux.org/alpine/v3.17/main\nhttp://nl.alpinelinux.org/alpine/v3.17/community" > /etc/apk/repositories
    - apk update && apk add python3 make g++
    - apk add --update nodejs npm
    - npm install -g npm
    - npm install --legacy-peer-deps
    - npm install react-scripts -g --silent
    - npm install nodemon -g --silent
  artifacts:
    expire_in: 1hr
    paths:
      - node_modules/
  cache:
    paths:
      - node_modules/

build-docker:
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
    CRYPTOGRAPHY_DONT_BUILD_RUST: 1
  services:
  - docker:dind
  stage: docker
  environment: staging
  cache:
    paths:
      - node_modules/
  dependencies:
    - install-dependencies
    - test-app
  script:
    - echo "Build docker 🐳"
    - docker build . -t=reactjs-weather-with-classes-app:gitlab-build-${CI_PIPELINE_IID}
  artifacts:
    expire_in: 1hr
    paths:
      - build

build-app:
  stage: build
  environment: staging
  cache:
    paths:
      - node_modules/
  dependencies:
    - install-dependencies
    - build-docker
  script:
    - npm run build:ci
  artifacts:
    expire_in: 1hr
    paths:
      - build

pages:
  stage: deploy
  environment: staging
  dependencies:
    - build-app
  script:
    - echo "Deploy a review app 🚀"
    - rm -rf public
    - cp build/index.html build/404.html
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - branches