version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: develop.Dockerfile
    container_name: reactjs-weather-with-classes-app
    volumes:
      - ".:/app"
    env_file:
      - .env.dev
    ports:
      - "3001:3000"
    tty: true