apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2024-01-17T00:18:34Z"
  generation: 1
  labels:
    app: reactjs-weather-with-classes-app
  name: reactjs-weather-with-classes-app
  namespace: default
  resourceVersion: "2465"
  uid: a4bd81a7-4682-41e8-a19d-1855aa3eec09
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: reactjs-weather-with-classes-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: reactjs-weather-with-classes-app
    spec:
      containers:
      - image: caprilespe/reactjs-weather-with-classes-app:1.0.0
        imagePullPolicy: IfNotPresent
        name: reactjs-weather-with-classes-app
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-01-17T00:18:40Z"
    lastUpdateTime: "2024-01-17T00:18:40Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-01-17T00:18:34Z"
    lastUpdateTime: "2024-01-17T00:18:40Z"
    message: ReplicaSet "reactjs-weather-with-classes-app-65bc8f9c47" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
